#!/usr/bin/env python3
import socket

if __name__ == "__main__":
    # Establish socket connection
    addr = ('webcrawler-site.ccs.neu.edu', 80)
    http_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    http_sock.connect(addr)

    